### ISSUE TITLE
peekToken can be null if the solver is interrupted/killed

### ISSUE THREAD

**Issue by colder** [regb/scala-smtlib#14]
[Warning ] Interrupted...
    java.lang.NullPointerException
        at smtlib.parser.ParserTerms$class.parseSExpr(ParserTerms.scala:308)
        at smtlib.parser.Parser.parseSExpr(Parser.scala:8)

**Comment by regb** [comment]
should be fixed in bb25bb91dfcf1f680c0d6fd7eee9840c6fb5d64b
